/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 26 05:44:13 GMT 2022
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Target_ESTest extends Target_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Target target0 = new Target();
      int[] intArray0 = new int[6];
      byte[] byteArray0 = new byte[3];
      byteArray0[0] = (byte) (-99);
      // Undeclared exception!
      try { 
        target0.__target__(byteArray0, intArray0, intArray0, 2, 1078);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 3 out of bounds for length 3
         //
         verifyException("Target", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Target target0 = new Target();
      byte[] byteArray0 = new byte[7];
      byteArray0[1] = (byte)1;
      int[] intArray0 = new int[9];
      // Undeclared exception!
      try { 
        target0.__target__(byteArray0, intArray0, intArray0, (byte)1, (byte)1);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 7 out of bounds for length 7
         //
         verifyException("Target", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Target target0 = new Target();
      byte[] byteArray0 = new byte[5];
      // Undeclared exception!
      try { 
        target0.__target__(byteArray0, (int[]) null, (int[]) null, (-1), (-1));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Target", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Target target0 = new Target();
      byte[] byteArray0 = new byte[5];
      int[] intArray0 = new int[1];
      boolean boolean0 = target0.__target__(byteArray0, intArray0, intArray0, (byte)1, (byte)1);
      assertArrayEquals(new int[] {0}, intArray0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      byte[] byteArray0 = new byte[18];
      Target target0 = new Target();
      int[] intArray0 = new int[6];
      int[] intArray1 = new int[9];
      intArray1[0] = (-2547);
      intArray1[1] = (-4213);
      boolean boolean0 = target0.__target__(byteArray0, intArray0, intArray1, 4, 1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      byte[] byteArray0 = new byte[5];
      int[] intArray0 = new int[4];
      intArray0[0] = 1;
      Target target0 = new Target();
      boolean boolean0 = target0.__target__(byteArray0, intArray0, intArray0, 4, 1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      byte[] byteArray0 = new byte[5];
      int[] intArray0 = new int[4];
      Target target0 = new Target();
      boolean boolean0 = target0.__target__(byteArray0, intArray0, (int[]) null, 4, 1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Target target0 = new Target();
      byte[] byteArray0 = new byte[12];
      int[] intArray0 = new int[20];
      // Undeclared exception!
      try { 
        target0.__target__(byteArray0, intArray0, intArray0, 3, 3);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 12 out of bounds for length 12
         //
         verifyException("Target", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Target target0 = new Target();
      byte[] byteArray0 = new byte[18];
      int[] intArray0 = new int[3];
      boolean boolean0 = target0.__target__(byteArray0, intArray0, intArray0, 3, 3);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Target target0 = new Target();
      byte[] byteArray0 = new byte[5];
      int[] intArray0 = new int[1];
      boolean boolean0 = target0.__target__(byteArray0, intArray0, (int[]) null, 2, (-1));
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      byte[] byteArray0 = new byte[5];
      int[] intArray0 = new int[4];
      Target target0 = new Target();
      target0.__target__(byteArray0, intArray0, intArray0, 0, 1);
      assertArrayEquals(new int[] {0, 0, 0, 0}, intArray0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Target target0 = new Target();
      byte[] byteArray0 = new byte[5];
      int[] intArray0 = new int[5];
      boolean boolean0 = target0.__target__(byteArray0, intArray0, intArray0, (-1110), 754);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Target target0 = new Target();
      byte[] byteArray0 = new byte[5];
      int[] intArray0 = new int[3];
      boolean boolean0 = target0.__target__(byteArray0, intArray0, (int[]) null, 3, (byte)1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Target target0 = new Target();
      byte[] byteArray0 = new byte[6];
      int[] intArray0 = new int[9];
      // Undeclared exception!
      try { 
        target0.__target__(byteArray0, intArray0, intArray0, (byte)1, (-1572));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 1572 out of bounds for length 9
         //
         verifyException("Target", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Target target0 = new Target();
      byte[] byteArray0 = new byte[5];
      int[] intArray0 = new int[5];
      boolean boolean0 = target0.__target__(byteArray0, intArray0, intArray0, 2, 27);
      assertArrayEquals(new int[] {0, 0, 0, 0, 0}, intArray0);
      assertTrue(boolean0);
  }
}
