/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 26 01:11:50 GMT 2022
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Target_ESTest extends Target_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Target target0 = new Target();
      byte[] byteArray0 = new byte[7];
      int[] intArray0 = new int[1];
      intArray0[0] = 16777215;
      byte[] byteArray1 = target0.__target__(intArray0, byteArray0);
      assertEquals(13, byteArray1.length);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Target target0 = new Target();
      int[] intArray0 = new int[5];
      intArray0[4] = 65535;
      byte[] byteArray0 = new byte[9];
      byte[] byteArray1 = target0.__target__(intArray0, byteArray0);
      assertEquals(22, byteArray1.length);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Target target0 = new Target();
      int[] intArray0 = new int[7];
      intArray0[6] = 255;
      byte[] byteArray0 = new byte[3];
      byte[] byteArray1 = target0.__target__(intArray0, byteArray0);
      assertEquals(13, byteArray1.length);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Target target0 = new Target();
      byte[] byteArray0 = new byte[3];
      // Undeclared exception!
      try { 
        target0.__target__((int[]) null, byteArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Target", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      byte[] byteArray0 = new byte[1];
      Target target0 = new Target();
      int[] intArray0 = new int[0];
      // Undeclared exception!
      try { 
        target0.__target__(intArray0, byteArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index -1 out of bounds for length 0
         //
         verifyException("Target", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Target target0 = new Target();
      int[] intArray0 = new int[5];
      intArray0[4] = 16777202;
      byte[] byteArray0 = new byte[4];
      byte[] byteArray1 = target0.__target__(intArray0, byteArray0);
      assertEquals(22, byteArray1.length);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Target target0 = new Target();
      byte[] byteArray0 = new byte[0];
      int[] intArray0 = new int[1];
      intArray0[0] = 401;
      byte[] byteArray1 = target0.__target__(intArray0, byteArray0);
      assertArrayEquals(new byte[] {(byte)0, (byte)0, (byte)2, (byte)0, (byte)1}, byteArray1);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Target target0 = new Target();
      int[] intArray0 = new int[7];
      byte[] byteArray0 = new byte[3];
      byte[] byteArray1 = target0.__target__(intArray0, byteArray0);
      assertEquals(13, byteArray1.length);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Target target0 = new Target();
      byte[] byteArray0 = new byte[9];
      int[] intArray0 = new int[1];
      intArray0[0] = 16777239;
      byte[] byteArray1 = target0.__target__(intArray0, byteArray0);
      assertEquals(16, byteArray1.length);
  }
}
