/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 29 13:35:40 GMT 2022
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Target_ESTest extends Target_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Target target0 = new Target();
      double[] doubleArray0 = new double[8];
      doubleArray0[1] = (double) 1;
      double double0 = target0.__target__(doubleArray0, 2, (-187.8), (-1669.42102226));
      assertEquals(0.005324964613653686, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Target target0 = new Target();
      double[] doubleArray0 = new double[8];
      doubleArray0[1] = (double) 1;
      double double0 = target0.__target__(doubleArray0, 8, (-187.8), 4871.0);
      assertEquals((-187.8), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Target target0 = new Target();
      double[] doubleArray0 = new double[8];
      doubleArray0[0] = 4871.0;
      double double0 = target0.__target__(doubleArray0, 1, 1390.903, 1.0);
      assertEquals(4871.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Target target0 = new Target();
      double[] doubleArray0 = new double[8];
      doubleArray0[0] = 4871.0;
      double double0 = target0.__target__(doubleArray0, 2, (-187.8), (-1669.42102226));
      assertEquals((-0.13811449751388233), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Target target0 = new Target();
      // Undeclared exception!
      try { 
        target0.__target__((double[]) null, 114, 7.47131, 114);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Target", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Target target0 = new Target();
      double[] doubleArray0 = new double[3];
      // Undeclared exception!
      try { 
        target0.__target__(doubleArray0, (-2142060709), 3857.43143909, 0.0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index -2142060710 out of bounds for length 3
         //
         verifyException("Target", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Target target0 = new Target();
      double[] doubleArray0 = new double[8];
      double double0 = target0.__target__(doubleArray0, 8, (-187.8), 4871.0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Target target0 = new Target();
      double[] doubleArray0 = new double[3];
      double double0 = target0.__target__(doubleArray0, 3, (-1.0), 2250.9880682894714);
      assertEquals(Double.NaN, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Target target0 = new Target();
      double[] doubleArray0 = new double[3];
      double double0 = target0.__target__(doubleArray0, 1, 0.0, (-3115.12525));
      assertEquals(0.0, double0, 0.01);
  }
}
